eventus/apps/events/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from views import IndexView,MainPanelView,CreateEvent,EventDetail,EventEdit,EventDelete

#index, main_panel,crear_evento,detalle_evento,editar_evento,eliminar_evento


urlpatterns = [
	#vistas basadas en clases
	url(r'^$',IndexView.as_view(), name= 'index'),
	#url(r'^login/$',login,name='login'),
	url(r'^panel/$',MainPanelView.as_view(), name= 'panel'),
	url(r'^panel/evento/nuevo/$',CreateEvent.as_view(), name= 'nuevo'),
	url(r'^panel/evento/(?P<pk>\d+)/$',EventDetail.as_view(), name= 'detalle'),
 	url(r'^panel/evento/editar/(?P<pk>\d+)/$',EventEdit.as_view(), name= 'editar'),
	url(r'^panel/evento/eliminar/(?P<pk>\d+)/$',EventDelete.as_view(), name= 'eliminar'),
]

eventus/apps/users/urls.py
from django.conf.urls import url, include
from views import userlogin,LogOut

urlpatterns = [

	url(r'^login/',userlogin,name='login'),
	url(r'^salir/',LogOut,name='logout'),

]

eventus/eventus/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve

from django.contrib.staticfiles.storage import staticfiles_storage
staticfiles_storage.url('events/static')


urlpatterns = [
	url(r'^', include('apps.events.urls', namespace="events_app")),
    url(r'^', include('apps.users.urls', namespace="users_app")),

    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

eventus/apps/events/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.template.defaultfilters import slugify 
from django.conf import settings

# Create your models here.

class TimeStampModel(models.Model):
	created=models.DateTimeField(auto_now_add=True)
	modified=models.DateTimeField(auto_now=True)

	class Meta:
		abstract=True#no se crea una tabla al migrar

class Category(models.Model):
	name=models.CharField(max_length=50)
	slug=models.SlugField(editable=False)
	def save(self, *args, **kwargs):
		if not self.id:
			self.slug = slugify(self.name)
		super(Category, self).save(*args, **kwargs)

	def __unicode__(self):#en v3 va __str__
		return self.name

class Event(TimeStampModel):
	name= models.CharField(max_length=200,unique=True)
	slug=models.SlugField(editable=False)
	summary=models.TextField(max_length=255)
	content=models.TextField()
	category= models.ForeignKey(Category)
	place=models.CharField(max_length=50)
	start=models.DateTimeField()
	finish=models.DateTimeField()
	imagen=models.ImageField(upload_to='events')#!
	is_free=models.BooleanField(default=True)
	amount=models.DecimalField(max_digits=5,decimal_places=2, default=0.00)
	views=models.PositiveIntegerField(default=0, blank=True, null=True)
	organizer=models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)#!


	def save(self, *args, **kwargs):
		if not self.id:
			self.slug=slugify(self.name)
		super(Event,self).save(*args,**kwargs)

	def __unicode__(self):#en v3 va __str__
		return self.name

class Assistant(TimeStampModel):
	assistant=models.ForeignKey(settings.AUTH_USER_MODEL)#!
	event=models.ManyToManyField(Event)

	attended=models.BooleanField(default=False)
	has_paid=models.BooleanField(default=False)

	def __unicode__(self):#en v3 va __str__
		return '%s %s' %(self.assistant.username,self.event.name)


class Comments(TimeStampModel):
	user=models.ForeignKey(settings.AUTH_USER_MODEL)
	event=models.ForeignKey(Event)
	content=models.TextField()
	def __unicode__(self):#en v3 va __str__
		return '%s %s' %(self.user.username,self.event.name)

eventus/apps/events/forms.py
from django import forms
from .models import Event

class EventoForm(forms.ModelForm):
	class Meta:
		model=Event
		#crea los formularios en automatico
		#el exclude evita los atributos que no deben ser generados por
		#el usuario
		#quitar organizer
		exclude=('views','created','modified',)
		widgets={
		'name':forms.TextInput(attrs={'class':'form-control'}),
		'summary':forms.Textarea(attrs={'class':'form-control','rows':'2'}),
		'content':forms.Textarea(attrs={'class':'form-control','rows':'2'}),
		'category':forms.Select(attrs={'class':'form-control'}),
		'place':forms.TextInput(attrs={'class':'form-control'}),
		'start':forms.DateTimeInput(attrs={'class':'form-control'}),
		'finish':forms.DateTimeInput(attrs={'class':'form-control'}),
		'imagen':forms.ClearableFileInput(attrs={'class':'form-control'}),
		'is_free':forms.CheckboxInput(attrs={'class':'form-control'}),
		'amount':forms.NumberInput(attrs={'class':'form-control'}),
		}
  

eventus/apps/events/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,redirect,get_object_or_404
from models import Event, Category
from forms import EventoForm
from django.core.urlresolvers import reverse,reverse_lazy
from ..users.models import User
from django.views.generic import TemplateView,CreateView,DetailView,UpdateView,DeleteView

# def login(request):
# 	return render(request,"login.html",{})

class IndexView(TemplateView):
	template_name='events/index.html'

	def get_context_data(self, **kwargs):
	    context = super(IndexView, self).get_context_data(**kwargs)
	    #obtiene las variables(contexto) para desplegar
	    context['events']=Event.objects.all().order_by('-created')[:6]
	    context['categories']=Category.objects.all()

	    return context


class MainPanelView(TemplateView):
	template_name='events/panel/panel.html'

	def get_context_data(self, **kwargs):
	    context = super(MainPanelView, self).get_context_data(**kwargs)
	    context['events'] = Event.objects.filter(organizer = self.request.user ).order_by('is_free', '-created')	   	#context['events']=Event.objects.filter(organizer__username='victorvillazon').order_by('is_free','-created')
	    context['cantidad']=context['events'].count()
	   	#hay diferencia ()?? si
	    return context		

class CreateEvent(CreateView):
	form_class=EventoForm
	template_name='events/panel/crear_evento.html'
	#reverse abre otra pagina en automatico
	#para evitar eso usamos reverse lazy
	success_url=reverse_lazy('events_app:panel')

	def form_valid(self,form):
		print 'es valido'
		#usar un request para usar el logeado, mientras esto :v
		#form.instance.organizer=User.objects.get(pk=1)
		#aqui le pasamos sel por que es la variable a majnejar en este momento
		form.instance.organizer=self.request.user
		return super(CreateEvent,self).form_valid(form)

# def crear_evento(request):
# 	if request.method=='POST':
# 		modelform=EventoForm(request.POST,request.FILES)
# 		if modelform.is_valid():
# 			organizador=User.objects.get(pk=3)
# 			print organizador
# 			nuevo_evento=modelform.save()
# 			nuevo_evento.organizer=organizador
# 			nuevo_evento.save()
# 			#el name space definido y su vsta
# 			return redirect(reverse('events_app:panel'))
# 	else:
# 		modelform=EventoForm()
# 	return render(request,'events/panel/crear_evento.html',{'form':modelform})


class EventDetail(DetailView):
	template_name='events/panel/detalle_evento.html'
	#creo que lo lee asi por sus huevos :v
	model=Event
# def detalle_evento(request,evento_id):
# 	event=get_object_or_404(Event,pk=evento_id)
# 	return render(request,'events/panel/detalle_evento.html',{'event':event})



class EventEdit(UpdateView):
	#me parece que las views manejan el model en automatico cn 
	#las solicitudes a la bd y al modelo
    model = Event
    form_class=EventoForm

    template_name = 'events/panel/editar_evento.html'
    success_url=reverse_lazy('events_app:panel')

    #para la edicion el mismo problema del usuario
    def form_valid(self,form):
    	#form.instance.organizer=User.objects.get(pk=3)
    	form.instance.organizer=self.request.user
    	return super(EventEdit,self).form_valid(form)
# def editar_evento(request,evento_id):
# 	event=get_object_or_404(Event,pk=evento_id)
# 	if request.method=='POST':
# 		#la instancia es para comparar si ya estaba o es nuevo el cambio
# 		modelform=EventoForm(request.POST,request.FILES,instance=event)
# 		if modelform.is_valid():
# 			modelform.save()
# 			return redirect(reverse('events_app:panel'))
# 	#si no fue enviada la peticion rellenar el formulario
# 	else:
# 		modelform=EventoForm(instance=event)
# #se le pasa eventen el cntexto para que el html lo despliegue
# 	return render(request,'events/panel/editar_evento.html',{'form':modelform, 'event':event})

class EventDelete(DeleteView):
 	model = Event
	template_name = 'events/panel/eliminar_evento.html'
	success_url=reverse_lazy('events_app:panel')
	#evento a eliminar
	context_object_name='event'


# def eliminar_evento(request,evento_id):
# 	event=get_object_or_404(Event,pk=evento_id)
# 	if request.method=='POST':
# 		event.delete()
# 		return redirect(reverse('events_app:panel'))
# 	return render(request,'events/panel/eliminar_evento.html',{'event':event})

eventus/apps/events/templates/events/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}
		
	{% endblock title %}</title>
</head>
{% block css %}
	
{% endblock css %}
<body>
{% block content %}
	
{% endblock content %} 
{% block js %}
	
{% endblock js %}
</body>
</html>

eventus/apps/events/templates/events/base_events.html
{% extends "base.html" %}
{% load staticfiles %}
{% block css %}
	<link rel="stylesheet" type="text/css" href="
	{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="
	{% static 'css/estilos.css' %}">
{% endblock css %}
{% block js %}
		<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
	{% endblock js %}	

eventus/apps/events/templates/events/index.html
{% extends "events/base_events.html" %}
{% block title %} Home
	
{% endblock title %}
{% block content %}
	

<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Eventus</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav pull-right">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'events_app:panel' %}">Hola {{ user.username|capfirst }}</a></li>
                {% else %}
                <li><a href="{% url 'users_app:login' %}">Sign Up / Login</a></li>
                {% endif %}
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>

<div class="jumbotron">
  <div class="container text-center">
    <h1>EVENTUS</h1>
    <p>Bienvenido a EVENTUS, aquí podrás encontrar eventos que se den en tu ciudad e inscribirte on-line con un solo click.</p>
    <p>¡<a href="{% url 'users_app:login' %}" role="button">Registrate</a> y crea tu evento ahora!</p>
  </div>
</div>

<div class="container">

    <div class="page-header">
        <h4><strong>Eventos disponibles</strong></h4>
    </div>

    <div class="row">
        
        <div class="col-md-2">
            <div class="input-group">
                <span class="input-group-addon"><span class="glyphicon glyphicon-tag"></span></span>
                <select class="form-control">
                    <option>Categoría</option>
                </select>
            </div>
        </div>
        <div class="col-md-2">
            <div class="input-group">
                <span class="input-group-addon"><span class="glyphicon glyphicon-credit-card"></span></span>
            <select class="form-control">
                <option>Tipo pago</option>
            </select>
            </div>
        </div>
        <div class="col-md-8">
            <div class="input-group">
                <span class="input-group-addon"><span class="glyphicon glyphicon-search"></span></span>
                <input type="text" class="form-control" placeholder="Busca el evento de tu gusto">
            </div>
        </div>

    </div>

</div>

<p></p>

<div class="container eventos">    
    
    <div class="row contenedor-eventos">
        {% for event in events %}
        <div class="col-sm-1 col-md-3 ">
            <div class="thumbnail equal">
                <img src="{{ event.imagen.url }}" alt="250x180">
                <div class="caption">
                    <h4><a href="">{{ event.name }}</a></h4>
                    <small class="date">{{ event.start }}</small>
                    <div class="place">
                        <small class="place">{{ event.place}}</small> / 
                    </div>
                    <span class="views">{{ event.views }}</span>
                </div>
            </div>
        </div>
        {% endfor %}
        
    </div>

</div>

<div class="container categorias">    

    <div class="page-header">
        <h4><strong>Categorías relacionadas</strong></h4>
    </div>

    <div class="row">
        <div class="col-sm-1 col-md-12">
        {% for category in categories %}
            <a class="btn btn-default btn-lg btn-fix">
                <span class="glyphicon glyphicon-tag"></span> {{ category.name }}
            </a>
        {% endfor %}
        </div>

    </div>

</div>

<div class="container organizadores">    

    <div class="page-header">
        <h4><strong>Organizadores destacados</strong></h4>
    </div>

    <div class="row">

        <div class="col-sm-1 col-md-2">
            <div class="thumbnail">
                <img src="http://placehold.it/300x180" alt="250x180">
                <div class="caption">
                    Nombre organizador
                </div>
            </div>
        </div>

    </div>

</div>

{% endblock content %}}